/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.controledelaudos.view.form;

import java.awt.Rectangle;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author CMR
 */
public class FormSistema extends javax.swing.JFrame {

    /**
     * Creates new form FormSistema
     */
    public FormSistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        abrirFormInternosNoCentroDaAreaDeTrabalho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPrestadores = new javax.swing.JMenuItem();
        menuProcedimentos = new javax.swing.JMenuItem();
        menuProfissionais = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Laudos CMR");

        javax.swing.GroupLayout AreaDeTrabalhoLayout = new javax.swing.GroupLayout(AreaDeTrabalho);
        AreaDeTrabalho.setLayout(AreaDeTrabalhoLayout);
        AreaDeTrabalhoLayout.setHorizontalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        AreaDeTrabalhoLayout.setVerticalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        jMenu1.setText("Iniciar");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        menuPrestadores.setText("Prestadores");
        menuPrestadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrestadoresActionPerformed(evt);
            }
        });
        jMenu2.add(menuPrestadores);

        menuProcedimentos.setText("Procedimentos");
        menuProcedimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcedimentosActionPerformed(evt);
            }
        });
        jMenu2.add(menuProcedimentos);

        menuProfissionais.setText("Profissionais");
        menuProfissionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfissionaisActionPerformed(evt);
            }
        });
        jMenu2.add(menuProfissionais);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AreaDeTrabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AreaDeTrabalho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPrestadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrestadoresActionPerformed
        abrirFormularioPrestador();
    }//GEN-LAST:event_menuPrestadoresActionPerformed

    private void menuProcedimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcedimentosActionPerformed
        abrirFormularioProcedimento();
    }//GEN-LAST:event_menuProcedimentosActionPerformed

    private void menuProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfissionaisActionPerformed
        abrirFormularioProfissional();
    }//GEN-LAST:event_menuProfissionaisActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new FormSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaDeTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuPrestadores;
    private javax.swing.JMenuItem menuProcedimentos;
    private javax.swing.JMenuItem menuProfissionais;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables

    private void abrirFormInternosNoCentroDaAreaDeTrabalho() {
        this.AreaDeTrabalho.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentResized(ComponentEvent e) {
                JInternalFrame[] iframes = getAreaDeTrabalho().getAllFrames();
                for (JInternalFrame iframe : iframes) {
                    if (iframe.isVisible()) {
                        int lDesk = getAreaDeTrabalho().getWidth();
                        int aDesk = getAreaDeTrabalho().getHeight();
                        int lIFrame = iframe.getWidth();
                        int aIFrame = iframe.getHeight();

                        iframe.setLocation(lDesk / 2 - lIFrame / 2, aDesk / 2 - aIFrame / 2);
                    }
                }
            }
        });
    }

    //ADICIONA TELAS (JInternalFrame) AO JDesktopPane  
    // usado assim: this.addTelaDesk(new TelaFuncionarios(null));  
    public final void abrirFormulario(JInternalFrame tela) {
        for (JInternalFrame jInternalFrame : this.getAreaDeTrabalho().getAllFrames()) {
            // se uma janela semelhante estiver aberta  
            if (jInternalFrame.getClass().toString().equalsIgnoreCase(tela.getClass().toString())) {
                jInternalFrame.moveToFront(); // traz janela para frente para facilitar a escolha  

                Object[] opções = {"Utilizar Aberta", "Abrir Nova"};
                int qst = JOptionPane.showOptionDialog(null, "Abrir uma nova janela ou utilizar a que ja esta aberta?",
                        "Janela duplicada",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        opções,
                        opções[0]
                );
                // se utilizar a aberta retorna e não abre outra,  
                // caso contrário sai do for e abre outra igual  
                if (qst == 0) {
                    return;
                } else if (qst == 1) {
                    break;
                }
            }
        }
        this.AreaDeTrabalho.add(tela); //adiciona na tela  
        tela.setVisible(true); // seta visivel  
        this.cascade(); //coloca em cascata para deixar "pratico"  

    }
    
    private void cascade() {
        JDesktopPane desk = this.getAreaDeTrabalho(); // JDesktopPane  
        Rectangle dBounds = desk.getBounds(); // Bordas do JDesktopPane  
        int separation = 25; // distancia entre as janelas  

        // Pega todos os frames e organiza, o ultimo fica mais em baido e mais pra cima  
        int i = desk.getAllFrames().length; // quantidade de frames  
        for (JInternalFrame f : desk.getAllFrames()) {
            f.setLocation(i * separation, i * separation);
            i--; //mutiplicador  
        }
    }
    
    private void abrirFormularioPrestador(){
        this.abrirFormulario(new FormCadPrestador());
    }
    
    private void abrirFormularioProcedimento(){
        this.abrirFormulario(new FormCadProcedimento());
    }
    
    private void abrirFormularioProfissional(){
        this.abrirFormulario(new FormCadProfissional());
    }

    public javax.swing.JDesktopPane getAreaDeTrabalho() {
        return AreaDeTrabalho;
    }

    public void setAreaDeTrabalho(javax.swing.JDesktopPane AreaDeTrabalho) {
        this.AreaDeTrabalho = AreaDeTrabalho;
    }
    
    
}
