/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.controledelaudos.view.form;

import com.controledelaudos.control.facade.ProfissionalFACADE;
import com.controledelaudos.model.beans.TabProfissional;
import com.controledelaudos.view.rn.ControleDeCaracteres;
import com.controledelaudos.view.tablemodels.ProfissionalTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author CMR
 */
public class FormCadProfissional extends javax.swing.JInternalFrame {

    private List<TabProfissional> listaProfissionais;
    private Integer codProfissional;
    private int linhaSelecionada;

    public FormCadProfissional() {
        initComponents();
        eventosDosBoes();
        habilitarBotoes(true);
        habilitarCampos(false);
        addListaProfissionalNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboCargo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProfissionais = new javax.swing.JTable();
        barraDeBtn1 = new com.controledelaudos.view.componentes.BarraDeBtn();

        setClosable(true);
        setIconifiable(true);
        setTitle("Profissionais");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Insira os dados do profissionais"));

        jLabel3.setText("SOBRENOME:");

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        txtID.setEnabled(false);

        jLabel2.setText("NOME:");

        jLabel1.setText("ID:");

        txtSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSobrenomeKeyTyped(evt);
            }
        });

        jLabel4.setText("CARGO:");

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o cargo...", "DIGITADOR", "MÉDICO", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtSobrenome))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de profissionais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setToolTipText("");

        tbProfissionais.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbProfissionais);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(barraDeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraDeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        ControleDeCaracteres.permitirSomenteTexto(evt);
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtSobrenomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSobrenomeKeyTyped
        ControleDeCaracteres.permitirSomenteTexto(evt);
    }//GEN-LAST:event_txtSobrenomeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.controledelaudos.view.componentes.BarraDeBtn barraDeBtn1;
    private javax.swing.JComboBox comboCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProfissionais;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables

    private void habilitarBotoes(boolean enabled) {
        barraDeBtn1.getBtnNovo().setEnabled(enabled);
        barraDeBtn1.getBtnSalvar().setEnabled(!enabled);
        barraDeBtn1.getBtnCancelar().setEnabled(!enabled);
        limparCampos();
    }

    private void habilitarCampos(boolean enabled) {
        txtNome.setEnabled(enabled);
        txtSobrenome.setEnabled(enabled);
        comboCargo.setEnabled(enabled);
    }

    private void limparCampos() {
        txtID.setText("");
        txtNome.setText("");
        txtSobrenome.setText("");
    }

    private void addListaProfissionalNaTabela() {
        listaProfissionais = new ProfissionalFACADE().listarTodosProfissionais();
        if (listaProfissionais != null) {
            tbProfissionais.setModel(new ProfissionalTableModel(listaProfissionais));

        }
    }

    private boolean validarCamposNoFomulário() {
        String campoNome = txtNome.getText();
        String campoSobrenome = txtSobrenome.getText();
        if ("".equals(campoNome)) {
            JOptionPane.showMessageDialog(this, "Campo `DESCRIÇÃO` obrigatório.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtNome.requestFocus();
            return false;
        } else if ("".equals(campoSobrenome)) {
            JOptionPane.showMessageDialog(this, "Campo `CÓDIGO` obrigatório.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtSobrenome.requestFocus();
            return false;
        }else if (comboCargo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Campo `CARGO` obrigatório.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void salvarOuAlterarProfissional() {
        if (!validarCamposNoFomulário()) {
            return;
        }

        String campoNome = txtNome.getText().toUpperCase();
        String campoSobrenome = txtSobrenome.getText().toUpperCase();
        String campoCargo = comboCargo.getSelectedItem().toString();
        TabProfissional profissional = new TabProfissional();
        profissional.setNome(campoNome);
        profissional.setSobrenome(campoSobrenome);
        profissional.setCargo(campoCargo);

        if (codProfissional == null) {
            new ProfissionalFACADE().salvarProfissional(profissional);
            JOptionPane.showMessageDialog(this, "Profissional salvo com sucesso.");
        } else {
            profissional.setCodProfissional(codProfissional);
            new ProfissionalFACADE().salvarProfissional(profissional);
            JOptionPane.showMessageDialog(this, "Profissional atualizado com sucesso.");
            codProfissional = null;
            habilitarBotoes(true);
            habilitarCampos(false);
        }
        addListaProfissionalNaTabela();
        limparCampos();
    }

    private boolean validarSeleçãoNaTabela(String msg) {
        linhaSelecionada = tbProfissionais.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, msg);
            return false;
        }
        return true;
    }

    private void prepararParaAtualizar() {
        String msg = "Selecione um registro para atualiza-lo.";
        if (!validarSeleçãoNaTabela(msg)) {
            return;
        }
        habilitarCampos(true);
        habilitarBotoes(false);
        TabProfissional profissional = new ProfissionalTableModel(listaProfissionais).get(linhaSelecionada);
        codProfissional = profissional.getCodProfissional();
        txtID.setText(String.valueOf(profissional.getCodProfissional()));
        txtNome.setText(profissional.getNome());
        txtSobrenome.setText(profissional.getSobrenome());
        comboCargo.setSelectedItem(profissional.getSobrenome());
    }

    private void excluir() {
        String msg = "Selecione um registro para remover.";
        if (!validarSeleçãoNaTabela(msg)) {
            return;
        }
        TabProfissional profissional = new ProfissionalTableModel(listaProfissionais).get(linhaSelecionada);
        int confirm = JOptionPane.showConfirmDialog(this, "Confirmar a exclusão? A exclusão do profissional " + profissional + " \n"
                + "pode apagar registros em outras partes do sistema.", "Excluir procedimento", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm != 0) {
            return;
        }
        new ProfissionalFACADE().removerProfissional(profissional);
        this.addListaProfissionalNaTabela();
    }

    private void eventosDosBoes() {
        //botão salvar
        barraDeBtn1.getBtnSalvar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                salvarOuAlterarProfissional();
            }
        });
        //botão novo
        barraDeBtn1.getBtnNovo().addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                habilitarBotoes(false);
                habilitarCampos(true);

            }
        });
        //botão atualizar
        barraDeBtn1.getBtnAtualizar().addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                prepararParaAtualizar();
            }
        });

        //botão cancelar
        barraDeBtn1.getBtnCancelar().addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                habilitarBotoes(true);
                habilitarCampos(false);
            }
        });

        //botão excluir
        barraDeBtn1.getBtnExcluir().addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                excluir();
            }
        });

    }

}
