/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.controledelaudos.view.form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author CMR
 */
public class FormTramitacaoLotes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormTramitacaoLotes
     */
    public FormTramitacaoLotes() {
        initComponents();
        inicializarAcoesButoes();
        //habilitarBotoes(true);
        desabilitarFormTodasEtapas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel4Etapa = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtDataSaida = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboSetorEncaminhado = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        comboSituacaoDoLote = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        radio2Etapa = new javax.swing.JRadioButton();
        radio1Etapa = new javax.swing.JRadioButton();
        radio3Etapa = new javax.swing.JRadioButton();
        radio4Etapa = new javax.swing.JRadioButton();
        painel1Etapa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboPrestador = new javax.swing.JComboBox();
        comboProcedimento = new javax.swing.JComboBox();
        txtQtdLote = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDataEntrada = new com.toedter.calendar.JDateChooser();
        painel2Etapa = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboMedicoRegulador = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtQtdNegada = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDataAnalise = new com.toedter.calendar.JDateChooser();
        painel3Etapa = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        comboDigitador = new javax.swing.JComboBox();
        txtQtdDigitada = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtDataDigitacao = new com.toedter.calendar.JDateChooser();
        painel4Etapa1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtDataSaida1 = new com.toedter.calendar.JDateChooser();

        painel4Etapa.setBorder(javax.swing.BorderFactory.createTitledBorder("4ª Etapa - Entrega ao prestador"));

        jLabel23.setText("Data de saída do lote:");

        jLabel24.setForeground(new java.awt.Color(51, 102, 255));
        jLabel24.setText("*Insira a data de entrega do lote.");

        javax.swing.GroupLayout painel4EtapaLayout = new javax.swing.GroupLayout(painel4Etapa);
        painel4Etapa.setLayout(painel4EtapaLayout);
        painel4EtapaLayout.setHorizontalGroup(
            painel4EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4EtapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel4EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel4EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel4EtapaLayout.setVerticalGroup(
            painel4EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4EtapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel4EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Atenção para os campos abaixo"));

        jLabel5.setText("Situação do lote:");

        jLabel25.setForeground(new java.awt.Color(255, 0, 51));
        jLabel25.setText("*Campo deve ser atualizado em cada etapa do processo.");

        jLabel6.setText("Setor encaminhado:");

        jLabel26.setForeground(new java.awt.Color(255, 0, 51));
        jLabel26.setText("*Campo deve ser atualizado em cada etapa do processo.");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a etapa do lote"));

        radio2Etapa.setText("2ª Etapa");
        radio2Etapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2EtapaActionPerformed(evt);
            }
        });

        radio1Etapa.setText("1ª Etapa");
        radio1Etapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1EtapaActionPerformed(evt);
            }
        });

        radio3Etapa.setText("3ª Etapa");
        radio3Etapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio3EtapaActionPerformed(evt);
            }
        });

        radio4Etapa.setText("4ª Etapa");
        radio4Etapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio4EtapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radio1Etapa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio2Etapa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio3Etapa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio4Etapa)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio1Etapa)
                    .addComponent(radio2Etapa)
                    .addComponent(radio3Etapa)
                    .addComponent(radio4Etapa)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSetorEncaminhado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(comboSituacaoDoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboSetorEncaminhado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(comboSituacaoDoLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))))
                .addContainerGap())
        );

        painel1Etapa.setBorder(javax.swing.BorderFactory.createTitledBorder("1ª Etapa - Entrada de Laudos na CMR"));

        jLabel1.setText("Data entrada:");

        jLabel2.setText("Prestador:");

        jLabel3.setText("Procedimento:");

        jLabel4.setText("QTD. do lote:");

        jLabel13.setForeground(new java.awt.Color(51, 102, 255));
        jLabel13.setText("*Insira a data de entrada do lote.");

        jLabel14.setForeground(new java.awt.Color(51, 102, 255));
        jLabel14.setText("*Selecione o prestador do referido lote.");

        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setText("*Selecione o procedimento do referido lote.");

        jLabel16.setForeground(new java.awt.Color(51, 102, 255));
        jLabel16.setText("*Insira a quantidade de laudos.");

        javax.swing.GroupLayout painel1EtapaLayout = new javax.swing.GroupLayout(painel1Etapa);
        painel1Etapa.setLayout(painel1EtapaLayout);
        painel1EtapaLayout.setHorizontalGroup(
            painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1EtapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1EtapaLayout.createSequentialGroup()
                        .addComponent(comboPrestador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(painel1EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)))
                .addGroup(painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdLote, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painel1EtapaLayout.setVerticalGroup(
            painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1EtapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(comboPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(comboProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtQtdLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel1EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel2Etapa.setBorder(javax.swing.BorderFactory.createTitledBorder("2ª Etapa  - Análise médica"));

        jLabel7.setText("Data análise:");

        jLabel8.setText("Médico regulador:");

        jLabel9.setText("QTD. negada:");

        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("*Insira a data que foi analisado.");

        jLabel11.setForeground(new java.awt.Color(51, 102, 255));
        jLabel11.setText("*Selecione o médico regulador que analisou o lote.");

        jLabel12.setForeground(new java.awt.Color(51, 102, 255));
        jLabel12.setText("*Insira a quantidade que foi negada se houver.");

        javax.swing.GroupLayout painel2EtapaLayout = new javax.swing.GroupLayout(painel2Etapa);
        painel2Etapa.setLayout(painel2EtapaLayout);
        painel2EtapaLayout.setHorizontalGroup(
            painel2EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2EtapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel2EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painel2EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(23, 23, 23))
                    .addGroup(painel2EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDataAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel2EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMedicoRegulador, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(painel2EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel2EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdNegada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel2EtapaLayout.setVerticalGroup(
            painel2EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2EtapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel2EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(comboMedicoRegulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtQtdNegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel2EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel3Etapa.setBorder(javax.swing.BorderFactory.createTitledBorder("3ª Etapa - Emissão de APAC"));

        jLabel17.setText("Data de digitação:");

        jLabel18.setText("Digitador:");

        jLabel19.setText("QTD. à ser digitada:");

        jLabel20.setForeground(new java.awt.Color(51, 102, 255));
        jLabel20.setText("*Insira a data de digtação do lote.");

        jLabel21.setForeground(new java.awt.Color(51, 102, 255));
        jLabel21.setText("*Selecione o digtador do referido lote.");

        jLabel22.setForeground(new java.awt.Color(51, 102, 255));
        jLabel22.setText("*Campo de preenchimento automático.");

        javax.swing.GroupLayout painel3EtapaLayout = new javax.swing.GroupLayout(painel3Etapa);
        painel3Etapa.setLayout(painel3EtapaLayout);
        painel3EtapaLayout.setHorizontalGroup(
            painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3EtapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel3EtapaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataDigitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel3EtapaLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addGroup(painel3EtapaLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboDigitador, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQtdDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel3EtapaLayout.setVerticalGroup(
            painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3EtapaLayout.createSequentialGroup()
                .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel3EtapaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtQtdDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboDigitador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))))
                    .addGroup(painel3EtapaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(txtDataDigitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(painel3EtapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel4Etapa1.setBorder(javax.swing.BorderFactory.createTitledBorder("4ª Etapa - Entrega ao prestador"));

        jLabel27.setText("Data de saída do lote:");

        jLabel28.setForeground(new java.awt.Color(51, 102, 255));
        jLabel28.setText("*Insira a data de entrega do lote.");

        javax.swing.GroupLayout painel4Etapa1Layout = new javax.swing.GroupLayout(painel4Etapa1);
        painel4Etapa1.setLayout(painel4Etapa1Layout);
        painel4Etapa1Layout.setHorizontalGroup(
            painel4Etapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4Etapa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel4Etapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel4Etapa1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataSaida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel4Etapa1Layout.setVerticalGroup(
            painel4Etapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4Etapa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel4Etapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(txtDataSaida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel1Etapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel2Etapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel3Etapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel4Etapa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel1Etapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel2Etapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel3Etapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel4Etapa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio2EtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2EtapaActionPerformed
        desabilitarHabiltarCampos1Etapa(false);
        desabilitarHabiltarCampos2Etapa(true);
        desabilitarHabiltarCampos3Etapa(false);
        desabilitarHabiltarCampos4Etapa(false);
    }//GEN-LAST:event_radio2EtapaActionPerformed

    private void radio1EtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1EtapaActionPerformed
        desabilitarHabiltarCampos1Etapa(true);
        desabilitarHabiltarCampos2Etapa(false);
        desabilitarHabiltarCampos3Etapa(false);
        desabilitarHabiltarCampos4Etapa(false);
    }//GEN-LAST:event_radio1EtapaActionPerformed

    private void radio3EtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio3EtapaActionPerformed
        desabilitarHabiltarCampos1Etapa(false);
        desabilitarHabiltarCampos2Etapa(false);
        desabilitarHabiltarCampos3Etapa(true);
        desabilitarHabiltarCampos4Etapa(false);
    }//GEN-LAST:event_radio3EtapaActionPerformed

    private void radio4EtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio4EtapaActionPerformed
        desabilitarHabiltarCampos1Etapa(false);
        desabilitarHabiltarCampos2Etapa(false);
        desabilitarHabiltarCampos3Etapa(false);
        desabilitarHabiltarCampos4Etapa(true);
    }//GEN-LAST:event_radio4EtapaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboDigitador;
    private javax.swing.JComboBox comboMedicoRegulador;
    private javax.swing.JComboBox comboPrestador;
    private javax.swing.JComboBox comboProcedimento;
    private javax.swing.JComboBox comboSetorEncaminhado;
    private javax.swing.JComboBox comboSituacaoDoLote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel painel1Etapa;
    private javax.swing.JPanel painel2Etapa;
    private javax.swing.JPanel painel3Etapa;
    private javax.swing.JPanel painel4Etapa;
    private javax.swing.JPanel painel4Etapa1;
    private javax.swing.JRadioButton radio1Etapa;
    private javax.swing.JRadioButton radio2Etapa;
    private javax.swing.JRadioButton radio3Etapa;
    private javax.swing.JRadioButton radio4Etapa;
    private com.toedter.calendar.JDateChooser txtDataAnalise;
    private com.toedter.calendar.JDateChooser txtDataDigitacao;
    private com.toedter.calendar.JDateChooser txtDataEntrada;
    private com.toedter.calendar.JDateChooser txtDataSaida;
    private com.toedter.calendar.JDateChooser txtDataSaida1;
    private javax.swing.JTextField txtQtdDigitada;
    private javax.swing.JTextField txtQtdLote;
    private javax.swing.JTextField txtQtdNegada;
    // End of variables declaration//GEN-END:variables

    private void desabilitarFormTodasEtapas() {
        desabilitarHabiltarCampos1Etapa(false);
        desabilitarHabiltarCampos2Etapa(false);
        desabilitarHabiltarCampos3Etapa(false);
        desabilitarHabiltarCampos4Etapa(false);
    }

    private void desabilitarHabiltarCampos1Etapa(boolean enabled) {
        txtDataEntrada.setEnabled(enabled);
        comboPrestador.setEnabled(enabled);
        comboProcedimento.setEnabled(enabled);
        txtQtdLote.setEnabled(enabled);
        txtDataEntrada.requestFocus();
    }

    private void desabilitarHabiltarCampos2Etapa(boolean enabled) {
        txtDataAnalise.setEnabled(enabled);
        comboMedicoRegulador.setEnabled(enabled);
        txtQtdNegada.setEnabled(enabled);
        txtDataAnalise.requestFocus();
    }

    private void desabilitarHabiltarCampos3Etapa(boolean enabled) {
        txtDataDigitacao.setEnabled(enabled);
        comboDigitador.setEnabled(enabled);
        txtQtdDigitada.setEnabled(enabled);
        txtDataDigitacao.requestFocus();
    }

    private void desabilitarHabiltarCampos4Etapa(boolean enabled) {
        txtDataSaida.setEnabled(enabled);
        txtDataSaida.requestFocus();
    }

    private void habilitarBotoes(boolean enabled) {
        barraDeBtn1.getBtnNovo().setEnabled(enabled);
        barraDeBtn1.getBtnSalvar().setEnabled(!enabled);
        barraDeBtn1.getBtnCancelar().setEnabled(!enabled);
    }

    private void inicializarAcoesButoes() {
        barraDeBtn1.getBtnNovo().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                onNovoRegistro();
            }
        });

        barraDeBtn1.getBtnCancelar().addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                onCancelarRegistro();
            }
        });

        barraDeBtn1.getBtnSalvar().addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                onSalvarOuAlterarRegistro();
            }
        });

        barraDeBtn1.getBtnAtualizar().addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                onAlterarRegistro();
            }
        });

        barraDeBtn1.getBtnExcluir().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                onExcluirRegistro();
            }
        });
    }

    private void onNovoRegistro() {

    }

    private void onCancelarRegistro() {

    }

    private void onSalvarOuAlterarRegistro() {

    }

    private void onAlterarRegistro() {

    }

    private void onExcluirRegistro() {

    }

}
